#!/bin/bash -l
#SBATCH --job-name=hpc-class             # job name
#SBATCH --time 00:30:00                  # wall-clock time (hrs:mins::secs)
#SBATCH --nodes=2                        # number of compute nodes
#SBATCH --ntasks=2                       # number of total MPI tasks
#SBATCH --ntasks-per-node=1
#SBATCH --error=job.%J.err               # error file name
#SBATCH --output=job.%J.out              # output file name
#SBATCH --exclusive

# load modules
module load openmpi

# your commands 
mpirun $@
